name: Build

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  precheck:
    runs-on: ubuntu-latest

    outputs:
      should_run: ${{ steps.stable-tag.outputs.should_run }}
      tag: ${{ steps.stable-tag.outputs.tag }}

    steps:
    - name: Get latest stable tag
      id: stable-tag
      run: |
        TAG=$(curl -s "https://api.github.com/repos/ghostty-org/ghostty/tags" | grep -Po  '"name": "\Kv[^"]*' | head -1)
        LAST_PROCESSED_TAG=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | grep -Po  '"tag_name": "\Kv[^"]*')

        echo "Latest build: $TAG"
        echo "Last built: $LAST_PROCESSED_TAG"

        if [ "$TAG" != "$LAST_PROCESSED_TAG" ]; then
          echo "should_run=true" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "New version found"
        else
          echo "should_run=false" > $GITHUB_OUTPUT
        fi

  build:
    strategy:
      matrix:
        os-version: ["22.04", "24.04"]

    runs-on: ubuntu-${{ matrix.os-version }}

    needs:
    - precheck

    if: ${{ needs.precheck.outputs.should_run == 'true' }}

    steps:

    - name: Set up zig
      uses: mlugg/setup-zig@v1
      with:
        version: 0.13.0

    - name: Install build deps
      run: sudo apt-get update && sudo apt-get install libgtk-4-dev libadwaita-1-dev

    - uses: actions/checkout@v4
      with:
        repository: ghostty-org/ghostty
        ref: ${{ steps.stable-tag.outputs.tag }}

    - name: Build
      run: |
        zig build -Doptimize=ReleaseFast
        mv zig-out/bin/ghostty zig-out/bin/ghostty_${{ matrix.os-version }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ghostty_${{ matrix.os-version }}
        path: zig-out/bin/ghostty_${{ matrix.os-version }}
        if-no-files-found: error

  release:
    runs-on: ubuntu-latest

    needs:
    - build

    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./dist/
        pattern: "ghostty_*"

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.precheck.outputs.tag }}
        body: https://github.com/ghostty-org/ghostty/releases/tag/${{ needs.precheck.outputs.tag }}
        fail_on_unmatched_files: true
        files: "dist/**/*"
